# -*- coding: utf-8 -*-
"""Data_ethics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10iGThdOiWy8hM5pLAncmDxjCaSF_ud7U
"""

import numpy as np
import pandas as pd
import json
import os

np.random.seed(42)

df_a = pd.read_excel("ShopNest_Privacy_Assessment_Datasets.xlsx", sheet_name="A_Original", parse_dates=["Date_of_Birth","Signup_Date"])
df_b = pd.read_excel("ShopNest_Privacy_Assessment_Datasets.xlsx", sheet_name="B_Auxiliary_Public", parse_dates=["Date_of_Birth"])

results = {}

qi_cols = ["Gender", "Date_of_Birth", "Pincode"]
grp = df_a.groupby(qi_cols).size().reset_index(name="count")
unique_qi_combos_baseline = (grp["count"] == 1).sum()
records_at_risk_baseline = df_a.merge(grp[grp["count"] == 1][qi_cols], on=qi_cols).shape[0]

results["baseline"] = {
    "n_records": len(df_a),
    "n_unique_qi_combinations": int(unique_qi_combos_baseline),
    "n_distinct_qi_combinations": int(len(grp)),
    "pct_records_uniquely_identifiable": round(100 * records_at_risk_baseline / len(df_a), 1),
}

direct_ids = ["Customer_ID", "Full_Name", "Email", "Phone_Number", "Last_Login_IP", "Card_Last4"]
df_a_deidentified = df_a.drop(columns=direct_ids)

merge_counts = df_a_deidentified.reset_index().merge(
    df_b[["Full_Name"] + qi_cols], on=qi_cols, how="inner"
).groupby("index").size()
unambiguous = (merge_counts == 1).sum()
any_match = merge_counts.shape[0]

results["after_direct_id_removal"] = {
    "n_records": len(df_a_deidentified),
    "records_with_at_least_one_linkage_match": int(any_match),
    "records_uniquely_reidentified": int(unambiguous),
    "pct_uniquely_reidentified": round(100 * unambiguous / len(df_a_deidentified), 1),
}

df_anon = df_a.copy()
rng = np.random.default_rng(7)
token_map = {cid: f"TKN-{rng.integers(10**9,10**10-1)}" for cid in df_anon["Customer_ID"].unique()}
df_anon["Customer_Token"] = df_anon["Customer_ID"].map(token_map)
df_anon = df_anon.drop(columns=["Customer_ID", "Full_Name", "Email", "Phone_Number",
                                 "Last_Login_IP", "Card_Last4"])
df_anon["Customer_Token_Masked"] = df_anon["Customer_Token"].apply(lambda t: t[:6] + "XXXX")

def age_band(dob, width):
    age = (pd.Timestamp("2026-01-01") - dob).days // width // 365 * width if False else None

def age_band(dob, width):
    age = (pd.Timestamp("2026-01-01") - dob).days // 365
    lower = (age // width) * width
    return f"{lower}-{lower+width-1}"

K = 4
GEN_LEVELS = [
    {"label": "L0: 5-yr age band + 3-digit pincode region", "age_width": 5, "pin_digits": 3, "use_city_only": False},
    {"label": "L1: 10-yr age band + 3-digit pincode region", "age_width": 10, "pin_digits": 3, "use_city_only": False},
    {"label": "L2: 10-yr age band + 2-digit pincode region", "age_width": 10, "pin_digits": 2, "use_city_only": False},
    {"label": "L3: 10-yr age band + city only (pincode dropped)", "age_width": 10, "pin_digits": 0, "use_city_only": True},
]
MAX_ACCEPTABLE_SUPPRESSION_PCT = 20.0
qi_anon = ["Gender", "Age_Band", "Pincode_Region"]
chosen_level = None
for lvl in GEN_LEVELS:
    tmp = df_anon.copy()
    tmp["Age_Band"] = df_a["Date_of_Birth"].apply(lambda d: age_band(d, lvl["age_width"]))
    if lvl["use_city_only"]:
        tmp["Pincode_Region"] = "N/A-" + tmp["City"]
    else:
        tmp["Pincode_Region"] = tmp["Pincode"].astype(str).str[:lvl["pin_digits"]] + "X" * (6 - lvl["pin_digits"])
    grp_sizes = tmp.groupby(qi_anon).size().reset_index(name="grp_size")
    tmp = tmp.merge(grp_sizes, on=qi_anon, how="left")
    suppression_pct = 100 * (tmp["grp_size"] < K).sum() / len(tmp)
    if chosen_level is None:
        chosen_level = (lvl, tmp, suppression_pct)
    if suppression_pct <= MAX_ACCEPTABLE_SUPPRESSION_PCT:
        chosen_level = (lvl, tmp, suppression_pct)
        break
    chosen_level = (lvl, tmp, suppression_pct)

lvl_used, df_anon, suppression_pct_used = chosen_level
still_below_k = df_anon["grp_size"] < K
n_suppressed_records = int(still_below_k.sum())
df_anon_kanon = df_anon.loc[~still_below_k].drop(columns=["grp_size", "Pincode", "Date_of_Birth", "Customer_Token"]).reset_index(drop=True)
GENERALIZATION_LEVEL_USED = lvl_used["label"]

agg_table = df_a.groupby(["City", "Product_Category"]).agg(
    n_customers=("Customer_ID", "count"), avg_order_amount=("Order_Amount_INR", "mean"),
).reset_index()
agg_table["avg_order_amount"] = agg_table["avg_order_amount"].round(2)

noise = np.random.default_rng(11).normal(loc=1.0, scale=0.06, size=len(df_anon_kanon))
df_anon_kanon["Order_Amount_INR_Perturbed"] = (df_anon_kanon["Order_Amount_INR"] * noise).round(2)

epsilon = 0.5
true_count = int((df_a["Product_Category"] == "Electronics").sum())
sensitivity = 1
dp_noisy_counts = [true_count + np.random.laplace(0, sensitivity/epsilon) for _ in range(5)]

results["differential_privacy_demo"] = {
    "epsilon": epsilon, "true_count_electronics_buyers": true_count,
    "noisy_count_samples": [round(x, 1) for x in dp_noisy_counts],
}

# Create the 'data' directory if it doesn't exist
os.makedirs('data', exist_ok=True)
df_anon_kanon.to_csv("data/Dataset_A_anonymized.csv", index=False)
agg_table.to_csv("data/Dataset_A_aggregated_city_category.csv", index=False)

results["k_anonymity"] = {
    "k": K, "generalization_level_used": GENERALIZATION_LEVEL_USED,
    "records_before_suppression": len(df_a), "records_suppressed_below_k": n_suppressed_records,
    "pct_suppressed": round(suppression_pct_used, 1),
    "records_after_kanonymity": len(df_anon_kanon),
    "distinct_qi_groups_after": int(df_anon_kanon.groupby(qi_anon).ngroups),
}

df_b_gen = df_b.copy()
_aw = lvl_used["age_width"]
df_b_gen["Age_Band"] = df_b_gen["Date_of_Birth"].apply(lambda d: age_band(d, _aw))
if lvl_used["use_city_only"]:
    df_b_gen["Pincode_Region"] = "N/A-" + df_b_gen["City"]
else:
    _pd_ = lvl_used["pin_digits"]
    df_b_gen["Pincode_Region"] = df_b_gen["Pincode"].astype(str).str[:_pd_] + "X" * (6 - _pd_)

merge_counts_post = df_anon_kanon.reset_index().merge(
    df_b_gen[["Full_Name", "Gender", "Age_Band", "Pincode_Region"]],
    on=["Gender", "Age_Band", "Pincode_Region"], how="inner"
).groupby("index").size()
unambiguous_post = (merge_counts_post == 1).sum() if len(merge_counts_post) else 0
any_match_post = merge_counts_post.shape[0] if len(merge_counts_post) else 0

results["after_anonymization"] = {
    "n_records": len(df_anon_kanon),
    "records_with_at_least_one_linkage_match": int(any_match_post),
    "records_uniquely_reidentified": int(unambiguous_post),
    "pct_uniquely_reidentified": round(100 * unambiguous_post / len(df_anon_kanon), 2) if len(df_anon_kanon) else 0.0,
}

orig_mean = df_a["Order_Amount_INR"].mean()
anon_mean = df_anon_kanon["Order_Amount_INR_Perturbed"].mean()
orig_cat_dist = df_a["Product_Category"].value_counts(normalize=True).sort_index()
anon_cat_dist = df_anon_kanon["Product_Category"].value_counts(normalize=True).sort_index()
tv_distance = 0.5 * (orig_cat_dist.subtract(anon_cat_dist, fill_value=0).abs().sum())

results["utility"] = {
    "mean_order_amount_original": round(orig_mean, 2),
    "mean_order_amount_anonymized": round(anon_mean, 2),
    "pct_change_in_mean_order_amount": round(100 * (anon_mean - orig_mean) / orig_mean, 2),
    "category_distribution_total_variation_distance": round(float(tv_distance), 4),
    "records_lost_to_suppression_pct": round(100 * (len(df_a) - len(df_anon_kanon)) / len(df_a), 2),
    "generalization_level_applied": GENERALIZATION_LEVEL_USED,
}

# ---- Worked example for Section 8.1 (deterministic pick of a real ambiguous group) ----
example_group = df_anon_kanon.groupby(qi_anon).size().reset_index(name="n").sort_values("n").iloc[len(df_anon_kanon.groupby(qi_anon))//2]
results["worked_example"] = {
    "gender": example_group["Gender"], "age_band": example_group["Age_Band"],
    "pincode_region": example_group["Pincode_Region"], "group_size_in_anonymized_data": int(example_group["n"]),
}

with open("results.json", "w") as f:
    json.dump(results, f, indent=2)
print(json.dumps(results, indent=2))

import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import os

# Create the 'figures' directory if it doesn't exist
os.makedirs('figures', exist_ok=True)

with open("results.json") as f:
    r = json.load(f)

plt.rcParams.update({"font.size": 11, "axes.edgecolor": "#444444", "axes.grid": True,
                      "grid.alpha": 0.3, "grid.linestyle": "--"})

stages = ["Original\n(baseline)", "Direct IDs\nremoved only", "After full\nanonymization"]
pct_uniquely_identifiable = [
    r["baseline"]["pct_records_uniquely_identifiable"],
    r["after_direct_id_removal"]["pct_uniquely_reidentified"],
    r["after_anonymization"]["pct_uniquely_reidentified"],
]
colors = ["#c0392b", "#e67e22", "#27ae60"]
fig, ax = plt.subplots(figsize=(7.2, 4.2))
bars = ax.bar(stages, pct_uniquely_identifiable, color=colors, width=0.55)
for b, v in zip(bars, pct_uniquely_identifiable):
    ax.text(b.get_x() + b.get_width()/2, v + 1.5, f"{v}%", ha="center", fontsize=11, fontweight="bold")
ax.set_ylabel("Uniquely re-identifiable records (%)")
ax.set_title("Re-identification Risk Across Anonymization Stages\n(Tested linkage attack using Dataset B)")
ax.set_ylim(0, 110)
fig.tight_layout()
fig.savefig("figures/fig1_reidentification_risk.png", dpi=200)
plt.close(fig)

fig, ax1 = plt.subplots(figsize=(7.2, 4.2))
metrics = ["Records\nretained (%)", "Mean order value\npreserved (%)", "Category mix\npreserved (%)"]
values = [
    100 - r["utility"]["records_lost_to_suppression_pct"],
    100 - abs(r["utility"]["pct_change_in_mean_order_amount"]),
    100 - 100 * r["utility"]["category_distribution_total_variation_distance"],
]
bars = ax1.bar(metrics, values, color=["#2980b9", "#8e44ad", "#16a085"], width=0.5)
for b, v in zip(bars, values):
    ax1.text(b.get_x() + b.get_width()/2, v + 1.2, f"{v:.1f}%", ha="center", fontsize=11, fontweight="bold")
ax1.set_ylabel("Utility retained (%)")
ax1.set_ylim(0, 110)
ax1.set_title("Analytical Utility Retained After Anonymization")
fig.tight_layout()
fig.savefig("figures/fig2_utility_retained.png", dpi=200)
plt.close(fig)
print("Figures written.")
